db:
    mode: mysql
    db_name: "testfiber"
    host: 127.0.0.1
    port: 3306
    user: your username
    password: your password
redis:
    addr: "127.0.0.1:6379"
    password: your password
    db: 1
system:
    mode: debug
    host: 127.0.0.1
    port: 8000
    version: 1.0.1
    allow_origins:
        - http://localhost:3000
log:
    env: debug
    prefix: "app"
    filename: ./logs/app.log
    max_size: 100    # MB
    max_backups: 7
    max_age: 28
    compress: false
jwt:
    issuer: "your name"
    access_secret: "xxxxxxxxxx"
    refresh_secret: "xxxxxxxx"
    access_expire: 2   # 小时
    refresh_expire: 168 # 小时（7天）
upload:
    size: 2 # MB
    path: uploads/images
site:
    login:
        captcha: false